import {
  Swords,
  Skull,
  MessageCircle,
  Footprints,
  Zap,
  Shield,
  Rabbit,
  ArrowLeftRight,
  Sparkles,
  FlaskRound,
  HeartPulse,
  Sword,
  PackageOpen,
  Coins,
  HandCoins,
  TriangleAlert,
  Clock,
  Flame,
  Flag,
  Users,
  CloudSun,
  Hourglass,
  MapPin,
  ShieldAlert,
  Eye,
  EyeOff,
  Scroll,
  HandHeart,
} from "lucide-react"
import type { LucideIcon } from "lucide-react"

export const ICON_MAP: Record<string, LucideIcon> = {
  swords: Swords,
  skull: Skull,
  "message-circle": MessageCircle,
  footprints: Footprints,
  zap: Zap,
  shield: Shield,
  rabbit: Rabbit,
  "arrow-left-right": ArrowLeftRight,
  sparkles: Sparkles,
  "flask-round": FlaskRound,
  "heart-pulse": HeartPulse,
  sword: Sword,
  "package-open": PackageOpen,
  coins: Coins,
  "hand-coins": HandCoins,
  "alert-triangle": TriangleAlert,
  clock: Clock,
  flame: Flame,
  flag: Flag,
  users: Users,
  "cloud-sun": CloudSun,
  hourglass: Hourglass,
  "map-pin": MapPin,
  "shield-alert": ShieldAlert,
  eye: Eye,
  "eye-off": EyeOff,
  scroll: Scroll,
  "hand-heart": HandHeart,
}
